### ISSUE TITLE
.env file support

### ISSUE THREAD

**Issue by swasher** [jotaen/run.sh#11]
Can you add .env file support?

**Comment by jotaen** [comment]
I think I wouldn’t want to have `.env` file support built-in, but since a `.env` file just contains environment variables, it can be done with a one-liner at the top of the `run.sh` file:

```bash
source .env
```

This can also be done conditionally:

```bash
# Only source if the .env file exists:
[[ -f .env ]] && source .env

# Only source if the .env file exists, otherwise fall back to sourcing .dev.env
[[ -f .env ]] && source .env || source .dev.env
```

**Comment by swasher** [comment]
Oh, great, I will try! Thank you!
